# Generated by Django 5.0.7 on 2024-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numOfRoom', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('water', models.BooleanField()),
                ('electricity', models.BooleanField()),
                ('wifi', models.CharField(max_length=100)),
                ('bathroom', models.CharField(max_length=100)),
                ('otherDetails', models.CharField(max_length=100)),
            ],
        ),
    ]
