# Generated by Django 5.0.7 on 2024-08-03 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
