# Generated by Django 5.0.6 on 2024-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userType',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
