# Generated by Django 5.0.6 on 2024-08-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_profile_usertype_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(),
        ),
    ]
