# Generated by Django 5.0.6 on 2024-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_wifi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='createdAt',
            new_name='listedAt',
        ),
        migrations.AlterField(
            model_name='room',
            name='otherDetails',
            field=models.CharField(max_length=500),
        ),
    ]
