# Generated by Django 5.0.6 on 2024-08-28 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.usertype'),
        ),
    ]
