# Generated by Django 5.0.7 on 2024-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_registrationdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationdetails",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="registrationdetails",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="registrationdetails",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="registrationdetails",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
