# Generated by Django 5.0.7 on 2024-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_registrationdetails_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationdetails",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
