# Generated by Django 5.0.7 on 2024-10-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_registrationdetails_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationDetails',
        ),
    ]
