# Generated by Django 5.0.7 on 2024-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_roomdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
