# Generated by Django 5.0.7 on 2024-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_roomdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rooms/'),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/rooms/'),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/rooms/'),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/rooms/'),
        ),
    ]
