# Generated by Django 5.0.7 on 2024-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_roomdetails_image_roomdetails_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='bathroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='rent',
            field=models.IntegerField(default=0),
        ),
    ]
