# Generated by Django 5.0.7 on 2024-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_roomdetails_bathroom_roomdetails_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='other_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
