# Generated by Django 5.0.7 on 2024-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_roomdetails_other_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdetails',
            old_name='image',
            new_name='citizenshipBack',
        ),
        migrations.RenameField(
            model_name='registrationdetails',
            old_name='image1',
            new_name='citizenshipFront',
        ),
        migrations.RenameField(
            model_name='registrationdetails',
            old_name='image2',
            new_name='passportPhoto',
        ),
        migrations.RemoveField(
            model_name='registrationdetails',
            name='image3',
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
