# Generated by Django 5.0.7 on 2024-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_image_registrationdetails_citizenshipback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
