# Generated by Django 5.0.7 on 2024-11-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_room_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
