# Generated by Django 5.0.7 on 2024-11-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_chatmessage_options_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented', models.BooleanField(default=False)),
            ],
        ),
    ]
