# Generated by Django 5.0.7 on 2024-11-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rentedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedrooms',
            name='rented',
        ),
        migrations.AddField(
            model_name='rentedrooms',
            name='rent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rentedrooms',
            name='rent_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentedrooms',
            name='rent_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentedrooms',
            name='roomId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
