# Generated by Django 5.0.7 on 2024-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_rentedrooms_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
