# Generated by Django 5.0.7 on 2024-11-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_roomdetails_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='rent_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='rent_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
