# Generated by Django 5.0.7 on 2024-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_roomdetails_rent_from_roomdetails_rent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdetails',
            name='phoneNumber',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
