# Generated by Django 5.0.7 on 2024-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_roomdetails_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='bhk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
