# Generated by Django 5.0.7 on 2024-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_roomdetails_bhk'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='roomFlat',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
