# Generated by Django 5.0.7 on 2024-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_roomdetails_roomflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='floorNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomdetails',
            name='houseAge',
            field=models.IntegerField(default=1),
        ),
    ]
